### ISSUE TITLE
Notebook Issues and Bumper Export

### ISSUE THREAD

**Issue by dressel** [sisl/AA228FinalProject#2]
The Bumper sensor that is commented out is never exported, so students who tried to use the Bumper sensor instead of the Lidar sensor could not.

In that code block, you pass in sensor=Lidar(), when you should pass in sensor=sensor, using the sensor defined a couple of lines above.

**Comment by kunalmenda** [comment]
Thanks for the notice! Bumper is now being exported and sensor=Lidar() is now sensor=sensor.
